# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4e63b8dbade2cbd4412b9844bc4d64339078f36d7ec76555b49d454c1cbb135be8e8e6a071a330382fb76eec8004d780ed3948be058a96becfe3febd9bcc32a

test:
  secret_key_base: d88b76f8b7a016ba2a53dac8e9f8e87c8d89ae416af3a244e872357730035f3dd2fba1669b3b3cb8af0b1dfa0067edb26e3339553722f8dd69d2b7418ad48693

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
